apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
  namespace: example
spec:
  replicas: 5
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 300; echo 'Performing cleanup tasks before termination'; exit 1"]
